### ISSUE TITLE
Add `#pragma` and `#include` support

### ISSUE THREAD

**Issue by cryshado** [ton-foundation/vscode-func#1]
The new version of FunC (since [`0.2.0`](https://github.com/starlightduck/ton/tree/func_dev)) supports the following key expressions: `#pragma version` and `#include`.

Example:
```C
#pragma version ^0.2.0;

#include "utils/op.func";
#include "utils/storage.func";
```

**Comment by dvlkv** [comment]
Implemented in last release.
